version: "3.9"

services:
  api:
    image: helloworld-api:latest           
    deploy:
      replicas: 5
      endpoint_mode: dnsrr        
      resources:
        limits:                   
          cpus: "2.0"            
          memory: 512M   
    environment:
      - API_NAME={{.Task.Slot}}
      - AGENT_PORT=9999                   
    networks:
      - poc-net
    expose:                              
      - "5000"
      - "9999"

  haproxy:
    image: haproxy:2.9
    configs:
      - source: haproxy_cfg_v2
        target: /usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:80"                         
      - "8404:8404" 
      - "6000:6000"                      
    networks:
      - poc-net
    deploy:
      placement:
        constraints:
          - node.role == manager          

configs:
  haproxy_cfg_v2:
    file: ./haproxy/haproxy.cfg

networks:
  poc-net:
    driver: overlay
